import "./globals.css";
import { Inter } from "next/font/google";
import ForLayout from "../components/ForLayout";
import Providers from "../components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopcart-admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ForLayout>{children}</ForLayout>
        </Providers>
      </body>
    </html>
  );
}
